### ISSUE TITLE
CI修正

### ISSUE THREAD

**Issue by naoki-00-ito** [rowicy/web#16]
ブランチ名がmasterになっているのでmainに修正する

```yml
on:
  pull_request:
    branches:
      - develop
      - master
```
